export interface IColorToken {
	"brand.blue1": string,
	"brand.blue10": string,
	"brand.blue20": string,
	"brand.blue30": string,
	"brand.blue40": string,
	"brand.blue50": string,
	"brand.blue60": string,
	"brand.blue70": string,
	"brand.blue80": string,
	"brand.blue90": string,
	"brand.blue100": string,

	"grayScale.primary1": string,
	"grayScale.primary5": string,
	"grayScale.primary10": string,
	"grayScale.primary20": string,
	"grayScale.primary30": string,
	"grayScale.primary40": string,
	"grayScale.primary50": string,
	"grayScale.primary60": string,
	"grayScale.primary70": string,
	"grayScale.primary80": string,
	"grayScale.primary90": string,
	"grayScale.primary100": string,

	"system.positive1": string,
	"system.positive10": string,
	"system.positive20": string,
	"system.positive30": string,
	"system.positive40": string,
	"system.positive50": string,
	"system.positive60": string,
	"system.positive70": string,
	"system.positive80": string,
	"system.positive90": string,
	"system.positive100": string,

	"system.warning1": string,
	"system.warning10": string,
	"system.warning20": string,
	"system.warning30": string,
	"system.warning40": string,
	"system.warning50": string,
	"system.warning60": string,
	"system.warning70": string,
	"system.warning80": string,
	"system.warning90": string,
	"system.warning100": string,

	"system.negative1": string,
	"system.negative10": string,
	"system.negative20": string,
	"system.negative30": string,
	"system.negative40": string,
	"system.negative50": string,
	"system.negative60": string,
	"system.negative70": string,
	"system.negative80": string,
	"system.negative90": string,
	"system.negative100": string,
}

export interface IColor {
    light: IColorToken,
    dark: IColorToken
}